# Generated by Django 4.2.1 on 2023-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Book Title')),
                ('description', models.TextField(verbose_name='Book Description')),
                ('price', models.FloatField(verbose_name='Book price')),
            ],
        ),
    ]
