# Generated by Django 4.2.1 on 2023-05-23 15:18

import book.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_title', models.CharField(max_length=100, verbose_name='Author Name')),
                ('book_title', models.CharField(max_length=100, verbose_name='Book Name')),
                ('isbn', models.CharField(default=book.utils.create_auto_number, max_length=50, null=True, verbose_name='Book ISBN')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='book.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.isbn'),
        ),
    ]
